baseURL: "https://magenta-sable-1da286.netlify.app"
title: "Citizens Track Toolkit"
theme: "netlify-basic"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    languageCode: en-GB
    languageName: English
    contentDir: content/en
    weight: 1
    title: "Citizens Track Toolkit"
  es:
    languageCode: es-ES
    languageName: Español
    contentDir: content/es
    weight: 2
    title: "Citizens Track Toolkit (ES)"
  fr:
    languageCode: fr-FR
    languageName: Français
    contentDir: content/fr
    weight: 3
    title: "Citizens Track Toolkit (FR)"
  de:
    languageCode: de-DE
    languageName: Deutsch
    contentDir: content/de
    weight: 4
    title: "Citizens Track Toolkit (DE)"